services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    ports:
      - "${JELLYFIN_PORT:-8096}:8096"

    environment:
      - TZ=${TZ:-America/Sao_Paulo}

    volumes:
      - ./config/jellyfin:/config
      - ./media:/media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    ports:
      - "${QBITTORRENT_WEB_PORT:-8080}:8080"
      - "${QBITTORRENT_PORT:-6881}:6881"
      - "${QBITTORRENT_PORT:-6881}:6881/udp"

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}
      - WEBUI_PORT=8080

    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped

    ports:
      - "${RADARR_PORT:-7878}:7878"

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}

    volumes:
      - ./config/radarr:/config
      - ./media/filmes:/movies
      - ./downloads:/downloads
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped

    ports:
      - "${PROWLARR_PORT:-9696}:9696"

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}

    volumes:
      - ./config/prowlarr:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped

    ports:
      - "${SONARR_PORT:-8989}:8989"

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}

    volumes:
      - ./config/sonarr:/config
      - ./media/series:/tv
      - ./downloads:/downloads

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped

    ports:
      - "${BAZARR_PORT:-6767}:6767"

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}

    volumes:
      - ./config/bazarr:/config
      - ./media/filmes:/movies
      - ./media/series:/tv

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped

    ports:
      - "${JELLYSEERR_PORT:-5055}:5055"

    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - PORT=5055

    volumes:
      - ./config/jellyseerr:/app/config