services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    ports:
      - "${JELLYFIN_PORT:-8096}:8096"

    environment:
      - TZ=${TZ:-America/Sao_Paulo}

    volumes:
      - ./config/jellyfin:/config
      - ./media:/media